options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging (or switch to GCS if required)

artifacts:
  objects:
    location: gs://coherence-go-build-logs/artifacts/
    paths: ["**/scroll-api", "**/*.go"]

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/scroll-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/scroll-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'scroll-api',
      '--image', 'gcr.io/$PROJECT_ID/scroll-api',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]