
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _OPENAI_API_KEY: your-api-key
  _PROJECT_ID: your-project-id
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/scroll-api-repo/scroll-api',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/scroll-api-repo/scroll-api'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'scroll-api',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/scroll-api-repo/scroll-api',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
